# default false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

[app]
name = "GO LEARNING"

[server]
port = ":8080"

[redis]
server = "127.0.0.1"
port = 6379
# 空要加双引号
password = ""
db = 0
